-- Creación de la tabla para almacenar respuestas de formularios por ramo y carrera
CREATE TABLE respuestas_formulario_local (
    id SERIAL PRIMARY KEY,
    ramo_id INTEGER NOT NULL,
    carrera_id INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    semestre VARCHAR(20) NOT NULL,
    respondent_email VARCHAR(255) NOT NULL,
    pregunta_1_correo VARCHAR(255),
    pregunta_2_rut VARCHAR(20),
    pregunta_3_nombres VARCHAR(255),
    pregunta_4_apellidos VARCHAR(255),
    pregunta_5_carrera VARCHAR(255),
    pregunta_6_anio_ingreso INTEGER,
    pregunta_7_veces_curso VARCHAR(20),
    pregunta_8_nota_aprobacion DECIMAL(3, 2),
    pregunta_9_ayudantias TEXT,
    pregunta_10_experiencia_evaluaciones TEXT,
    pregunta_11_tutorias TEXT,
    pregunta_12_talleres_umdu TEXT,
    pregunta_13_nivel_riesgo VARCHAR(20),
    pregunta_14_motivo_ayudantia TEXT,
    pregunta_15_bloques_disponibles JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (respondent_email, ramo_id, carrera_id, anio, semestre),
    FOREIGN KEY (ramo_id) REFERENCES ramos(id),
    FOREIGN KEY (carrera_id) REFERENCES carreras(id)
);
